### PR TITLE
Add css selectors

### PR DESCRIPTION
**Pull request by rothsandro**
# Thank you for opening a pull request to tiny-teachers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-teachers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [x] you only add one (!) new teacher per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focused on a single, development related issue.
- [x] the `desc` field includes an "actionable sentence" (e.g. "Learn about CSS flexbox" or "Learn how to design well.").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
@rothsandro Heyooo, thanks for contributing to Tiny Helpers. :) 🙇‍♂️

I'm a little on the fence for this one. Might it be a better fit here: https://tiny-teachers.dev/?

**Comment by rothsandro** [comment]
Hi @stefanjudis, I'm confused... The PR is already for tiny teachers, not for tiny helpers.

**Comment by stefanjudis** [comment]
Oh boy... Silly me. 🤦‍♂️ You're right! happy to take it!

Too early over here to work on PRs I guess. Apologies. 😅

**Comment by stefanjudis** [comment]
FYI — i have to update node to deploy. Might take a while until it's going out. :/

**Comment by rothsandro** [comment]
No problem 👍 Thanks for merging and letting me know

**Comment by stefanjudis** [comment]
@rothsandro and live. :) Thanks again for contributing.

**Pull request merged**
